export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "./globals.css";
import { CartProvider } from "@/Context/CartContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
